### ISSUE TITLE
Fix HP_assemble_01 pipeline to handle updated Miniconda (I think)

### ISSUE THREAD

**Issue by kmgibson** [gwcbi/haphpipe#1]
Some issues are being thrown with when trying to run HP_assemble_01 pipeline. There are no errors thrown in the haphpipe.log output file. I can't get it to run on our testing data either.

```
[---haphpipe_assemble_01---] (Sun Oct  6 20:22:37 EDT 2019) assemble_amplicons command:
hp_assemble_amplicons --contigs_fa ./haphpipe_assemble_01/denovo_contigs.fna --ref_fa HIV_B.K03455.HXB2.amplicons.fasta --ref_gtf HIV_B.K03455.HXB2.gtf --sample_id uganda_test --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
Traceback (most recent call last):
  File "/GWSPH/home/kmgibson/.conda/envs/haphpipe/bin/hp_assemble_amplicons", line 10, in <module>
    sys.exit(console())
  File "/GWSPH/home/kmgibson/.conda/envs/haphpipe/lib/python3.7/site-packages/haphpipe/stages/assemble_amplicons.py", line 196, in console
    args.func(**sysutils.args_params(args))
  File "/GWSPH/home/kmgibson/.conda/envs/haphpipe/lib/python3.7/site-packages/haphpipe/stages/assemble_amplicons.py", line 121, in assemble_amplicons
    amp_e = min(len(refseqs[gl.chrom]), gl.end + padding)
KeyError: 'HIV_B.K03455.HXB2'
[---haphpipe_assemble_01---] (Sun Oct  6 20:22:37 EDT 2019) FAILED: assemble_amplicons
```

**Comment by kmgibson** [comment]
Error from Maggie running it too.
```
(haphpipe) [steinerm@node339 hpassemblerun2]$ haphpipe_assemble_01 PL-12_S3_L001_R1_001.fastq PL-12_S3_L001_R2_001.fastq HIV_B.K03455.HXB2.fasta HIV_B.K03455.HXB2_2.gtf sample12_2
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) read1:             PL-12_S3_L001_R1_001.fastq
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) read2:             PL-12_S3_L001_R2_001.fastq
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) reference_fasta:   HIV_B.K03455.HXB2.fasta
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) reference_gtf:     HIV_B.K03455.HXB2_2.gtf
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) samp_id:           sample12_2
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) outdir:            ./haphpipe_assemble_01
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) num CPU:           12
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) Stage: trim_reads
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:10 EDT 2019) trim_reads command:
hp_reads trim_reads --ncpu 12 --fq1 PL-12_S3_L001_R1_001.fastq --fq2 PL-12_S3_L001_R2_001.fastq --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:18 EDT 2019) COMPLETED: trim_reads
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:18 EDT 2019) Stage: ec_reads
[---haphpipe_assemble_01---] (Fri Oct 25 20:10:18 EDT 2019) ec_reads command:
hp_reads ec_reads --ncpu 12 --fq1 ./haphpipe_assemble_01/trimmed_1.fastq --fq2 ./haphpipe_assemble_01/trimmed_2.fastq --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
Traceback (most recent call last):
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/bin/hp_reads", line 10, in <module>
    sys.exit(console())
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/lib/python2.7/site-packages/haphpipe/reads.py", line 32, in console
    args.func(**sysutils.args_params(args))
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/lib/python2.7/site-packages/haphpipe/stages/ec_reads.py", line 118, in ec_reads
    d = yaml.load(fh, Loader=yaml.FullLoader)[0]
AttributeError: 'module' object has no attribute 'FullLoader'
[---haphpipe_assemble_01---] (Fri Oct 25 20:13:53 EDT 2019) FAILED: ec_reads
[---haphpipe_assemble_01---] (Fri Oct 25 20:13:53 EDT 2019) Stage: assemble_denovo
[---haphpipe_assemble_01---] (Fri Oct 25 20:13:53 EDT 2019) assemble_denovo command:
hp_assemble assemble_denovo --ncpu 12 --fq1 ./haphpipe_assemble_01/trimmed_1.fastq --fq2 ./haphpipe_assemble_01/trimmed_2.fastq --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:38 EDT 2019) COMPLETED: assemble_denovo
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:38 EDT 2019) Stage: assemble_amplicons
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:38 EDT 2019) assemble_amplicons command:
hp_assemble_amplicons --contigs_fa ./haphpipe_assemble_01/denovo_contigs.fna --ref_fa HIV_B.K03455.HXB2.fasta --ref_gtf HIV_B.K03455.HXB2_2.gtf --sample_id sample12_2 --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
Traceback (most recent call last):
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/bin/hp_assemble_amplicons", line 10, in <module>
    sys.exit(console())
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/lib/python2.7/site-packages/haphpipe/stages/assemble_amplicons.py", line 192, in console
    args.func(**sysutils.args_params(args))
  File "/groups/cbi/shared/apps/miniconda3/4.3.27.1/envs/haphpipe/lib/python2.7/site-packages/haphpipe/stages/assemble_amplicons.py", line 162, in assemble_amplicons
    file=logfile)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 55-56: ordinal not in range(128)
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) FAILED: assemble_amplicons
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) Stage: refine_assembly
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) refine_assembly command:
hp_refine_assembly --ncpu 12 --fq1 ./haphpipe_assemble_01/corrected_1.fastq --fq2 ./haphpipe_assemble_01/corrected_2.fastq --ref_fa ./haphpipe_assemble_01/amplicon_assembly.fna --sample_id sample12_2 --max_step 5 --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
usage: hp_refine_assembly [-h] [--fq1 FQ1] [--fq2 FQ2] [--fqU FQU] --ref_fa
                          REF_FA [--outdir OUTDIR] [--max_step MAX_STEP]
                          [--subsample SUBSAMPLE] [--seed SEED]
                          [--sample_id SAMPLE_ID] [--ncpu NCPU] [--xmx XMX]
                          [--keep_tmp] [--quiet] [--logfile LOGFILE] [--debug]
hp_refine_assembly: error: argument --fq1: ./haphpipe_assemble_01/corrected_1.fastq does not exist
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) FAILED: refine_assembly
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) Stage: finalize_assembly
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) finalize_assembly command:
hp_finalize_assembly --ncpu 12 --fq1 ./haphpipe_assemble_01/corrected_1.fastq --fq2 ./haphpipe_assemble_01/corrected_2.fastq --sample_id sample12_2 --ref_fa ./haphpipe_assemble_01/refined.fna --quiet --logfile ./haphpipe_assemble_01/haphpipe.out --outdir ./haphpipe_assemble_01
usage: hp_finalize_assembly [-h] [--fq1 FQ1] [--fq2 FQ2] [--fqU FQU] --ref_fa
                            REF_FA [--outdir OUTDIR]
                            [--bt2_preset {very-fast,fast,sensitive,very-sensitive,very-fast-local,fast-local,sensitive-local,very-sensitive-local}]
                            [--sample_id SAMPLE_ID] [--ncpu NCPU] [--keep_tmp]
                            [--quiet] [--logfile LOGFILE] [--debug]
hp_finalize_assembly: error: argument --fq1: ./haphpipe_assemble_01/corrected_1.fastq does not exist
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) FAILED: finalize_assembly
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) 24 minutes and 36 seconds elapsed.
[---haphpipe_assemble_01---] (Fri Oct 25 20:34:46 EDT 2019) haphpipe_assemble_01 COMPLETE.
```

**Comment by mlbendall** [comment]
@maggiesteiner This is failing because it is running python 2.7. The function signature for `yaml.load` is different in 2.7 and 3+.
